apiVersion: v1
kind: Secret

metadata:
  name: cloudflare-tunnel-secret
  namespace: netriun

type: Opaque

stringData:
  TUNNEL_TOKEN: eyJhIjoiMTZlY2Q2ZTVmMDRkMzVkZDlkNjM3MzczMTFlN2QwNzMiLCJ0IjoiNzYyZDczNzMtYTU5Zi00NzM2LTk4NjAtNWE1NGEyZTE1NTJhIiwicyI6Ik16UTNObU13TVdVdE56TXlOeTAwWlRNeExXSm1ORGt0WldRM05qQXpZekUzWldFeiJ9
#  docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMTZlY2Q2ZTVmMDRkMzVkZDlkNjM3MzczMTFlN2QwNzMiLCJ0IjoiOTRiOGQxMTQtNjZlZi00MGY0LWJkYTgtZGUxMTNjZjA4NzM2IiwicyI6Ik9HVmlPVGM0TldVdE1USTJOQzAwTkRaakxXSTNOR0l0TUdVeFpqVmpNVFptTlRGayJ9
#docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMTZlY2Q2ZTVmMDRkMzVkZDlkNjM3MzczMTFlN2QwNzMiLCJ0IjoiNzYyZDczNzMtYTU5Zi00NzM2LTk4NjAtNWE1NGEyZTE1NTJhIiwicyI6Ik16UTNObU13TVdVdE56TXlOeTAwWlRNeExXSm1ORGt0WldRM05qQXpZekUzWldFeiJ9